spring.application.name=aquatrack

spring.datasource.url=jdbc:postgresql://localhost:5432/aquatrack
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

#quando for deixar rodando com tudo ok trocar para validate**!!!
spring.jpa.hibernate.ddl-auto=update


