spring.application.name=aquatrack


# ===== BANCO DEV =====
spring.datasource.url=jdbc:postgresql://localhost:5432/aquatrack
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== EMAIL DEV (Mailtrap) =====
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=1d88800609de1c
spring.mail.password=da952dc308ea69
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.properties.mail.smtp.ssl.trust=smtp.mailtrap.io

#Domínio aquatrack (usado no link que vai no email)
aquaTrack.domain=https://localhost:8080