spring.application.name=aquatrack


#Banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/aquatrack
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
#quando for deixar rodando com tudo ok trocar para validate**!!!
spring.jpa.hibernate.ddl-auto=update

#Sistema de Email (Gmail para produção)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${AQUATRACK_MAIL_USERNAME}
spring.mail.password=${AQUATRACK_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

#Domínio aquatrack (usado no link que vai no email)
#quando mandar pra produção alterar para https://aquatrackpb.shop
aquaTrack.domain=http://localhost:8080
