spring.application.name=aquatrack


#Banco de dados
#porta 5432 = versão 18 (ainda incompatível com flyway) | porta 5433= versão 16 (compatível e funcional)
#Usando a versão 16 para ser mais estável e a mesma da produção
spring.datasource.url=jdbc:postgresql://localhost:5433/aquatrack
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
#quando for deixar rodando com tudo ok trocar para validate**!!!
#o auto gera o banco de dados automaticamente, no validate ele só valida, se nn tiver ok, não roda! nós que temos que criar com script sql
#validate é o mais certo e mais seguro para Produção
spring.jpa.hibernate.ddl-auto=update

#Sistema de Email (MailTrap para desenvolvimento)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=1d88800609de1c
spring.mail.password=da952dc308ea69
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.properties.mail.smtp.ssl.trust=smtp.mailtrap.io

#Domínio aquatrack (usado no link que vai no email)
aquaTrack.domain=http://localhost:8080

#Ativa o flyway pra configurar os arquivos de migrations
#migrations são tipo tipo scripts que funcionam como um histórico de comandos que rodam no bd
#os que já existem não podem ser alterados!
spring.flyway.enabled=true